# Generated by Django 3.0.8 on 2020-07-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoardGame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=144)),
            ],
            options={
                'ordering': ('username',),
            },
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
