# Generated by Django 3.0.8 on 2020-07-30 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoardGame', '0002_auto_20200728_2135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Usernames',
        ),
    ]
