# Generated by Django 3.0.8 on 2020-07-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoardGame', '0003_auto_20200730_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernames',
            name='username',
            field=models.CharField(blank=True, default='player', max_length=144, null=True, unique=True),
        ),
    ]
