# Generated by Django 3.0.8 on 2020-07-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoardGame', '0004_auto_20200730_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='imgUrl',
            field=models.URLField(max_length=400),
        ),
    ]
