# Generated by Django 3.0.4 on 2020-10-03 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BoardGame', '0004_auto_20201003_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='BoardGame.Game'),
        ),
    ]
