# Generated by Django 3.0.9 on 2020-08-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoardGame', '0005_auto_20200730_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernames',
            name='username',
            field=models.CharField(blank=True, default='player', max_length=144, null=True, unique=True, verbose_name='JSON'),
        ),
    ]
