# Generated by Django 3.0.9 on 2020-08-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoardGame', '0006_auto_20200803_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernames',
            name='username',
            field=models.CharField(blank=True, default='player', max_length=144, unique=True),
        ),
    ]
