# Generated by Django 3.0.9 on 2020-08-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoardGame', '0007_auto_20200810_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernames',
            name='username',
            field=models.CharField(max_length=144, unique=True),
        ),
    ]
