# Generated by Django 3.0.4 on 2020-09-30 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board_game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='playersNumber',
            new_name='maxPlayers',
        ),
        migrations.AlterField(
            model_name='match',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='board_game.Game'),
        ),
        migrations.AlterField(
            model_name='player',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='board_game.Match'),
        ),
    ]
