# Generated by Django 3.0.4 on 2020-09-30 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_game', '0002_auto_20200930_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='room',
            new_name='match',
        ),
    ]
