# Generated by Django 3.0.4 on 2020-11-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game', '0006_match_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectName',
            field=models.CharField(help_text='Category of games', max_length=100),
        ),
    ]
