# Generated by Django 3.0.4 on 2020-11-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game', '0010_auto_20201110_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('C', 'CREATED'), ('A', 'ACTIVE'), ('F', 'FINISHED')], default='C', max_length=144),
        ),
    ]
