# Generated by Django 3.0.4 on 2020-11-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game', '0011_match_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('ACTIVE', 'ACTIVE'), ('FINISHED', 'FINISHED')], default='CREATED', max_length=144),
        ),
    ]
