# Generated by Django 3.0.4 on 2021-01-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game', '0012_auto_20201125_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='mark',
            field=models.CharField(default='', max_length=144),
        ),
    ]
