# Generated by Django 3.0.4 on 2021-01-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game', '0013_player_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='currentPlayer',
            field=models.IntegerField(blank=True, default=None,null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='mark',
            field=models.CharField(blank=True, default='', max_length=144),
        ),
    ]
